# Generated by Django 2.1.5 on 2019-10-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('email', models.CharField(max_length=256, verbose_name='email')),
                ('valid_from', models.DateTimeField(verbose_name='valid_from')),
                ('valid_until', models.DateTimeField(verbose_name='valid_until')),
                ('payment_id', models.CharField(max_length=256, verbose_name='payment_id')),
                ('payment_address', models.CharField(max_length=256, verbose_name='payment_address')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=1000, verbose_name='amount')),
                ('request_origin', models.CharField(max_length=256, verbose_name='request_origin')),
                ('payment_status', models.CharField(max_length=256, verbose_name='payment_status')),
                ('voucher_generated', models.BooleanField(default=False, verbose_name='voucher_generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ('payment_id',),
            },
        ),
    ]
